# Generated by Django 2.2 on 2021-05-19 19:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communaute',
            name='abonnes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
