# Generated by Django 2.2 on 2021-05-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0003_post_priorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='titre',
            field=models.CharField(default='titre du post', max_length=50),
            preserve_default=False,
        ),
    ]
