# Generated by Django 2.2 on 2021-05-22 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0005_auto_20210522_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
