# Generated by Django 2.2 on 2021-05-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0007_auto_20210522_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_evenement',
            field=models.DateTimeField(null=models.BooleanField(default=False)),
        ),
        migrations.AlterField(
            model_name='post',
            name='evenementiel',
            field=models.BooleanField(default=False),
        ),
    ]
