# Generated by Django 2.2 on 2021-05-23 13:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communitymanager', '0014_auto_20210522_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 23, 13, 48, 34, 512316, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=datetime.datetime(2021, 5, 23, 13, 48, 34, 515077, tzinfo=utc))),
                ('contenu', models.TextField()),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communitymanager.Post')),
            ],
        ),
    ]
